/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * DoctorKhoj Healthcare Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Hospital {
  id: number;
  name: string;
  /** government or private */
  type: string;
  address: string;
  /** @nullable */
  phone?: string | null;
  specializations: string[];
  rating: number;
  totalDoctors: number;
  timings: string;
  /** @nullable */
  imageUrl?: string | null;
  createdAt: string;
}

export interface Doctor {
  id: number;
  name: string;
  specialization: string;
  hospitalId: number;
  /** @nullable */
  hospitalName?: string | null;
  qualification: string;
  /** Years of experience */
  experience: number;
  consultationFee: number;
  rating: number;
  availability: string[];
  timings: string;
  /** @nullable */
  imageUrl?: string | null;
  createdAt: string;
}

export interface Appointment {
  id: number;
  slipNumber: string;
  patientName: string;
  patientAge: number;
  patientGender: string;
  patientPhone: string;
  patientEmail: string;
  doctorId: number;
  /** @nullable */
  doctorName?: string | null;
  /** @nullable */
  hospitalName?: string | null;
  /** @nullable */
  specialization?: string | null;
  appointmentDate: string;
  appointmentTime: string;
  /** @nullable */
  symptoms?: string | null;
  /** pending, confirmed, completed, cancelled */
  status: string;
  /** unpaid, paid */
  paymentStatus: string;
  /** @nullable */
  paymentMethod?: string | null;
  /** @nullable */
  transactionId?: string | null;
  consultationFee: number;
  createdAt: string;
}

export interface CreateAppointmentBody {
  patientName: string;
  patientAge: number;
  patientGender: string;
  patientPhone: string;
  patientEmail: string;
  doctorId: number;
  appointmentDate: string;
  appointmentTime: string;
  symptoms?: string;
}

export interface PaymentBody {
  /** upi or card */
  paymentMethod: string;
  /** @nullable */
  upiId?: string | null;
  /** @nullable */
  cardNumber?: string | null;
}

export interface ChatbotSuggestBody {
  symptoms: string;
}

export interface ChatbotSuggestResponse {
  message: string;
  suggestedSpecialization: string;
  doctors: Doctor[];
}

export interface PlatformStats {
  totalHospitals: number;
  totalDoctors: number;
  totalAppointments: number;
  totalSpecializations: number;
}

export type ListHospitalsParams = {
  search?: string;
  type?: string;
  specialization?: string;
};

export type ListDoctorsParams = {
  search?: string;
  specialization?: string;
  hospitalId?: number;
};

export type ListAppointmentsParams = {
  patientEmail?: string;
};
