/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * DoctorKhoj Healthcare Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Appointment,
  ChatbotSuggestBody,
  ChatbotSuggestResponse,
  CreateAppointmentBody,
  Doctor,
  HealthStatus,
  Hospital,
  ListAppointmentsParams,
  ListDoctorsParams,
  ListHospitalsParams,
  PaymentBody,
  PlatformStats,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all hospitals
 */
export const getListHospitalsUrl = (params?: ListHospitalsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/hospitals?${stringifiedParams}`
    : `/api/hospitals`;
};

export const listHospitals = async (
  params?: ListHospitalsParams,
  options?: RequestInit,
): Promise<Hospital[]> => {
  return customFetch<Hospital[]>(getListHospitalsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListHospitalsQueryKey = (params?: ListHospitalsParams) => {
  return [`/api/hospitals`, ...(params ? [params] : [])] as const;
};

export const getListHospitalsQueryOptions = <
  TData = Awaited<ReturnType<typeof listHospitals>>,
  TError = ErrorType<unknown>,
>(
  params?: ListHospitalsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listHospitals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListHospitalsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listHospitals>>> = ({
    signal,
  }) => listHospitals(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listHospitals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListHospitalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listHospitals>>
>;
export type ListHospitalsQueryError = ErrorType<unknown>;

/**
 * @summary List all hospitals
 */

export function useListHospitals<
  TData = Awaited<ReturnType<typeof listHospitals>>,
  TError = ErrorType<unknown>,
>(
  params?: ListHospitalsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listHospitals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListHospitalsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get hospital by ID
 */
export const getGetHospitalUrl = (id: number) => {
  return `/api/hospitals/${id}`;
};

export const getHospital = async (
  id: number,
  options?: RequestInit,
): Promise<Hospital> => {
  return customFetch<Hospital>(getGetHospitalUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetHospitalQueryKey = (id: number) => {
  return [`/api/hospitals/${id}`] as const;
};

export const getGetHospitalQueryOptions = <
  TData = Awaited<ReturnType<typeof getHospital>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHospital>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHospitalQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHospital>>> = ({
    signal,
  }) => getHospital(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHospital>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHospitalQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHospital>>
>;
export type GetHospitalQueryError = ErrorType<void>;

/**
 * @summary Get hospital by ID
 */

export function useGetHospital<
  TData = Awaited<ReturnType<typeof getHospital>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHospital>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHospitalQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all doctors
 */
export const getListDoctorsUrl = (params?: ListDoctorsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/doctors?${stringifiedParams}`
    : `/api/doctors`;
};

export const listDoctors = async (
  params?: ListDoctorsParams,
  options?: RequestInit,
): Promise<Doctor[]> => {
  return customFetch<Doctor[]>(getListDoctorsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListDoctorsQueryKey = (params?: ListDoctorsParams) => {
  return [`/api/doctors`, ...(params ? [params] : [])] as const;
};

export const getListDoctorsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDoctors>>,
  TError = ErrorType<unknown>,
>(
  params?: ListDoctorsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDoctors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDoctorsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDoctors>>> = ({
    signal,
  }) => listDoctors(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDoctors>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDoctorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDoctors>>
>;
export type ListDoctorsQueryError = ErrorType<unknown>;

/**
 * @summary List all doctors
 */

export function useListDoctors<
  TData = Awaited<ReturnType<typeof listDoctors>>,
  TError = ErrorType<unknown>,
>(
  params?: ListDoctorsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDoctors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDoctorsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get doctor by ID
 */
export const getGetDoctorUrl = (id: number) => {
  return `/api/doctors/${id}`;
};

export const getDoctor = async (
  id: number,
  options?: RequestInit,
): Promise<Doctor> => {
  return customFetch<Doctor>(getGetDoctorUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetDoctorQueryKey = (id: number) => {
  return [`/api/doctors/${id}`] as const;
};

export const getGetDoctorQueryOptions = <
  TData = Awaited<ReturnType<typeof getDoctor>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDoctor>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDoctorQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDoctor>>> = ({
    signal,
  }) => getDoctor(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getDoctor>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetDoctorQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDoctor>>
>;
export type GetDoctorQueryError = ErrorType<void>;

/**
 * @summary Get doctor by ID
 */

export function useGetDoctor<
  TData = Awaited<ReturnType<typeof getDoctor>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDoctor>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDoctorQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List appointments (optionally for a patient)
 */
export const getListAppointmentsUrl = (params?: ListAppointmentsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/appointments?${stringifiedParams}`
    : `/api/appointments`;
};

export const listAppointments = async (
  params?: ListAppointmentsParams,
  options?: RequestInit,
): Promise<Appointment[]> => {
  return customFetch<Appointment[]>(getListAppointmentsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListAppointmentsQueryKey = (
  params?: ListAppointmentsParams,
) => {
  return [`/api/appointments`, ...(params ? [params] : [])] as const;
};

export const getListAppointmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAppointments>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAppointmentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAppointments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListAppointmentsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAppointments>>
  > = ({ signal }) => listAppointments(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAppointments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAppointmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAppointments>>
>;
export type ListAppointmentsQueryError = ErrorType<unknown>;

/**
 * @summary List appointments (optionally for a patient)
 */

export function useListAppointments<
  TData = Awaited<ReturnType<typeof listAppointments>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAppointmentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAppointments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAppointmentsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Book an appointment
 */
export const getCreateAppointmentUrl = () => {
  return `/api/appointments`;
};

export const createAppointment = async (
  createAppointmentBody: CreateAppointmentBody,
  options?: RequestInit,
): Promise<Appointment> => {
  return customFetch<Appointment>(getCreateAppointmentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAppointmentBody),
  });
};

export const getCreateAppointmentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAppointment>>,
    TError,
    { data: BodyType<CreateAppointmentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAppointment>>,
  TError,
  { data: BodyType<CreateAppointmentBody> },
  TContext
> => {
  const mutationKey = ["createAppointment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAppointment>>,
    { data: BodyType<CreateAppointmentBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createAppointment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAppointmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAppointment>>
>;
export type CreateAppointmentMutationBody = BodyType<CreateAppointmentBody>;
export type CreateAppointmentMutationError = ErrorType<void>;

/**
 * @summary Book an appointment
 */
export const useCreateAppointment = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAppointment>>,
    TError,
    { data: BodyType<CreateAppointmentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAppointment>>,
  TError,
  { data: BodyType<CreateAppointmentBody> },
  TContext
> => {
  return useMutation(getCreateAppointmentMutationOptions(options));
};

/**
 * @summary Get appointment by ID
 */
export const getGetAppointmentUrl = (id: number) => {
  return `/api/appointments/${id}`;
};

export const getAppointment = async (
  id: number,
  options?: RequestInit,
): Promise<Appointment> => {
  return customFetch<Appointment>(getGetAppointmentUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetAppointmentQueryKey = (id: number) => {
  return [`/api/appointments/${id}`] as const;
};

export const getGetAppointmentQueryOptions = <
  TData = Awaited<ReturnType<typeof getAppointment>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAppointment>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppointmentQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppointment>>> = ({
    signal,
  }) => getAppointment(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAppointment>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAppointmentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAppointment>>
>;
export type GetAppointmentQueryError = ErrorType<void>;

/**
 * @summary Get appointment by ID
 */

export function useGetAppointment<
  TData = Awaited<ReturnType<typeof getAppointment>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAppointment>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAppointmentQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Process payment for appointment
 */
export const getPayAppointmentUrl = (id: number) => {
  return `/api/appointments/${id}/pay`;
};

export const payAppointment = async (
  id: number,
  paymentBody: PaymentBody,
  options?: RequestInit,
): Promise<Appointment> => {
  return customFetch<Appointment>(getPayAppointmentUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(paymentBody),
  });
};

export const getPayAppointmentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof payAppointment>>,
    TError,
    { id: number; data: BodyType<PaymentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof payAppointment>>,
  TError,
  { id: number; data: BodyType<PaymentBody> },
  TContext
> => {
  const mutationKey = ["payAppointment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof payAppointment>>,
    { id: number; data: BodyType<PaymentBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return payAppointment(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PayAppointmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof payAppointment>>
>;
export type PayAppointmentMutationBody = BodyType<PaymentBody>;
export type PayAppointmentMutationError = ErrorType<void>;

/**
 * @summary Process payment for appointment
 */
export const usePayAppointment = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof payAppointment>>,
    TError,
    { id: number; data: BodyType<PaymentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof payAppointment>>,
  TError,
  { id: number; data: BodyType<PaymentBody> },
  TContext
> => {
  return useMutation(getPayAppointmentMutationOptions(options));
};

/**
 * @summary AI chatbot - suggest specialization and doctors based on symptoms
 */
export const getChatbotSuggestUrl = () => {
  return `/api/chatbot/suggest`;
};

export const chatbotSuggest = async (
  chatbotSuggestBody: ChatbotSuggestBody,
  options?: RequestInit,
): Promise<ChatbotSuggestResponse> => {
  return customFetch<ChatbotSuggestResponse>(getChatbotSuggestUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chatbotSuggestBody),
  });
};

export const getChatbotSuggestMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatbotSuggest>>,
    TError,
    { data: BodyType<ChatbotSuggestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatbotSuggest>>,
  TError,
  { data: BodyType<ChatbotSuggestBody> },
  TContext
> => {
  const mutationKey = ["chatbotSuggest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatbotSuggest>>,
    { data: BodyType<ChatbotSuggestBody> }
  > = (props) => {
    const { data } = props ?? {};

    return chatbotSuggest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatbotSuggestMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatbotSuggest>>
>;
export type ChatbotSuggestMutationBody = BodyType<ChatbotSuggestBody>;
export type ChatbotSuggestMutationError = ErrorType<unknown>;

/**
 * @summary AI chatbot - suggest specialization and doctors based on symptoms
 */
export const useChatbotSuggest = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatbotSuggest>>,
    TError,
    { data: BodyType<ChatbotSuggestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof chatbotSuggest>>,
  TError,
  { data: BodyType<ChatbotSuggestBody> },
  TContext
> => {
  return useMutation(getChatbotSuggestMutationOptions(options));
};

/**
 * @summary Get platform statistics
 */
export const getGetPlatformStatsUrl = () => {
  return `/api/stats`;
};

export const getPlatformStats = async (
  options?: RequestInit,
): Promise<PlatformStats> => {
  return customFetch<PlatformStats>(getGetPlatformStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPlatformStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetPlatformStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlatformStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlatformStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPlatformStats>>
  > = ({ signal }) => getPlatformStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPlatformStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlatformStats>>
>;
export type GetPlatformStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get platform statistics
 */

export function useGetPlatformStats<
  TData = Awaited<ReturnType<typeof getPlatformStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPlatformStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get featured/top-rated doctors for homepage
 */
export const getGetFeaturedDoctorsUrl = () => {
  return `/api/doctors/featured`;
};

export const getFeaturedDoctors = async (
  options?: RequestInit,
): Promise<Doctor[]> => {
  return customFetch<Doctor[]>(getGetFeaturedDoctorsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFeaturedDoctorsQueryKey = () => {
  return [`/api/doctors/featured`] as const;
};

export const getGetFeaturedDoctorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeaturedDoctors>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedDoctors>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeaturedDoctorsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFeaturedDoctors>>
  > = ({ signal }) => getFeaturedDoctors({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedDoctors>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFeaturedDoctorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeaturedDoctors>>
>;
export type GetFeaturedDoctorsQueryError = ErrorType<unknown>;

/**
 * @summary Get featured/top-rated doctors for homepage
 */

export function useGetFeaturedDoctors<
  TData = Awaited<ReturnType<typeof getFeaturedDoctors>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedDoctors>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFeaturedDoctorsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get featured hospitals for homepage
 */
export const getGetFeaturedHospitalsUrl = () => {
  return `/api/hospitals/featured`;
};

export const getFeaturedHospitals = async (
  options?: RequestInit,
): Promise<Hospital[]> => {
  return customFetch<Hospital[]>(getGetFeaturedHospitalsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFeaturedHospitalsQueryKey = () => {
  return [`/api/hospitals/featured`] as const;
};

export const getGetFeaturedHospitalsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeaturedHospitals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedHospitals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeaturedHospitalsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFeaturedHospitals>>
  > = ({ signal }) => getFeaturedHospitals({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedHospitals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFeaturedHospitalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeaturedHospitals>>
>;
export type GetFeaturedHospitalsQueryError = ErrorType<unknown>;

/**
 * @summary Get featured hospitals for homepage
 */

export function useGetFeaturedHospitals<
  TData = Awaited<ReturnType<typeof getFeaturedHospitals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedHospitals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFeaturedHospitalsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
